name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: "openjdk@1.17.0"

      - name: Run tests
        run: sbt compile
        shell: bash
