name: Release

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "openjdk@1.17.0"

      - name: Package plugin
        run: sbt publish